name: inventosmart
description: InventoSmart - GST Inventory & Billing for Indian MSMEs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # HTTP client
  dio: ^5.4.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Barcode scanner
  mobile_scanner:  ^7.2.0
  
  # Date/number formatting
  intl: ^0.19.0
  url_launcher: ^6.2.4
  fl_chart: ^0.68.0
 
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true